# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  feature/JIRA-1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: './hello.ps1'
    arguments: '-greeter "$(Build.RequestedFor)" -trigger "$(Build.QueuedBy)" '