trigger:
- features/JIRA-1


pool:

  name: Azure Pipelines

steps:

- task: PowerShell@2

  displayName: 'PowerShell Script'

  inputs:

    targetType: filePath

    filePath: ./hellow.ps1

    arguments: '-greeter "$(Build.RequestedFor)" -trigger "$(Build.QueuedBy)" '
